title: Hola mundo! Bienvenidos al blog de xescodes para ser un TAI
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Xescodes # add your name
author-img: 8307975.jpeg # add your photo
about-author: Soy un recepcionista con alma al 40% filósofo, 30% desarrollador y 30% friky
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: xescodes # add your Github handle
social-linkedin: https://www.linkedin.com/in/xesco/# add your Linkedin handle
social-email: francesc@xescodes.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
